'use client'

import { useState } from 'react'
import { AlertTriangle, CalendarClock, ClipboardList, Package, Settings, Truck } from 'lucide-react'
import { formatCurrency } from '@/lib/currency'
import { expiringBatches, intakeSessions, lowStockProducts } from '@/lib/demo/selectors'
import type { DemoData } from '@/lib/demo/types'
import { DemoActionButton, DemoBadge, DemoCard, DemoPageHeader, DemoSearch, DemoSelect, DemoStatCard } from './demo-ui'

const money=(n:number)=>formatCurrency(n,'NGN')
const date=(s:string)=>new Intl.DateTimeFormat('en-NG',{dateStyle:'medium'}).format(new Date(s))

export function VendorsPreview({data,onAction}:{data:DemoData;onAction:(s:string)=>void}){
 const[q,setQ]=useState(''),[kind,setKind]=useState('all');const rows=data.vendors.filter(v=>(kind==='all'||v.type===kind)&&(v.name+v.contact).toLowerCase().includes(q.toLowerCase()))
 return <><DemoPageHeader eyebrow="Supply partners" title="Vendors" description="Review direct and consignment suppliers in this fictional store." action={<DemoActionButton onClick={()=>onAction('Create vendors')} icon={Truck}>Add Vendor</DemoActionButton>}/><DemoCard><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row"><DemoSearch value={q} onChange={setQ} placeholder="Search vendors"/><DemoSelect label="Type" value={kind} onChange={setKind} options={[{value:'all',label:'All types'},{value:'direct',label:'Direct'},{value:'consignment',label:'Consignment'}]}/></div><div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map(v=>{const batches=data.batches.filter(b=>b.vendorId===v.id);return <button key={v.id} onClick={()=>onAction('Edit vendor details')} className="rounded-xl border border-border bg-bg-nav p-4 text-left hover:border-accent-primary/50"><div className="flex justify-between gap-2"><strong>{v.name}</strong><DemoBadge tone={v.type==='consignment'?'teal':'orange'}>{v.type}</DemoBadge></div><p className="mt-3 text-xs text-text-secondary">{v.contact} · {v.phone}</p><p className="mt-2 text-xs text-text-muted">{batches.length} supplied batches · {batches.reduce((n,b)=>n+b.qtyRemaining,0)} units remaining</p></button>})}</div></DemoCard></>
}

export function IntakePreview({data,onAction}:{data:DemoData;onAction:(s:string)=>void}){
 const[q,setQ]=useState('');const names=new Map(data.products.map(p=>[p.id,p.name]));const rows=intakeSessions(data).filter(s=>(s.reference+s.vendorName).toLowerCase().includes(q.toLowerCase()))
 return <><DemoPageHeader eyebrow="Stock receiving" title="Intake history" description="Explore incoming stock, costs, vendors, and consignment batches." action={<DemoActionButton onClick={()=>onAction('Record stock intake')} icon={ClipboardList}>New Intake</DemoActionButton>}/><DemoCard><div className="border-b border-border p-4"><DemoSearch value={q} onChange={setQ} placeholder="Search intake or vendor"/></div><div className="divide-y divide-border-subtle">{rows.map(s=><details key={s.id} className="group px-4 py-4"><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3"><span><strong className="mono text-sm">{s.reference}</strong><small className="block text-text-muted">{date(s.receivedAt)} · {s.vendorName}</small></span><span className="text-right"><strong>{money(s.totalCost)}</strong><small className="block text-text-muted">{s.itemCount} products · {s.totalUnits} units</small></span></summary><div className="mt-4 grid gap-2 border-t border-border-subtle pt-4 sm:grid-cols-2">{s.batches.map(b=><div key={b.id} className="rounded-lg bg-bg-nav p-3 text-sm"><span>{names.get(b.productId)}</span><small className="block text-text-muted">{b.qtyReceived} received · {b.qtyRemaining} remaining · {money(b.costPerUnit)} each</small></div>)}</div></details>)}</div></DemoCard></>
}

export function AlertsPreview({data,onAction}:{data:DemoData;onAction:(s:string)=>void}){
 const low=lowStockProducts(data), expiring=expiringBatches(data), names=new Map(data.products.map(p=>[p.id,p.name])), now=new Date(data.generatedAt).getTime()
 return <><DemoPageHeader eyebrow="Action centre" title="Inventory alerts" description="Prioritise tracked products that need restocking and batches approaching expiry." action={<DemoActionButton onClick={()=>onAction('Configure alerts')} icon={AlertTriangle}>Alert settings</DemoActionButton>}/><div className="mb-5 grid gap-3 sm:grid-cols-2"><DemoStatCard label="Low stock products" value={String(low.length)} detail="At or below reorder level" icon={Package} tone="yellow"/><DemoStatCard label="Expiry risks" value={String(expiring.length)} detail="Expired or due within 30 days" icon={CalendarClock} tone="teal"/></div><div className="grid gap-5 xl:grid-cols-2"><DemoCard title="Low stock"><div className="divide-y divide-border-subtle">{low.map(p=><div key={p.id} className="flex justify-between px-4 py-3 text-sm"><span>{p.name}<small className="block text-text-muted">Reorder at {p.reorderLevel}</small></span><DemoBadge tone="warning">{p.stock} left</DemoBadge></div>)}</div></DemoCard><DemoCard title="Expiry risk"><div className="divide-y divide-border-subtle">{expiring.map(b=>{const d=Math.ceil((new Date((b.expiryDate||'')+'T00:00:00').getTime()-now)/86400000);return <div key={b.id} className="flex justify-between px-4 py-3 text-sm"><span>{names.get(b.productId)}<small className="block text-text-muted">{b.qtyRemaining} units · {b.reference}</small></span><DemoBadge tone={d<0?'danger':'warning'}>{d<0?Math.abs(d)+'d expired':d+'d left'}</DemoBadge></div>})}</div></DemoCard></div></>
}

export function SettingsPreview({data,onAction}:{data:DemoData;onAction:(s:string)=>void}){
 return <><DemoPageHeader eyebrow="Store configuration" title="Settings" description="A read-only look at store identity and desktop capabilities." action={<DemoActionButton onClick={()=>onAction('Update store settings')} icon={Settings}>Edit Settings</DemoActionButton>}/><div className="grid gap-5 xl:grid-cols-2"><DemoCard title="Store profile"><dl className="grid gap-5 p-5 text-sm sm:grid-cols-2"><div><dt className="text-xs text-text-muted">Store name</dt><dd className="mt-1 font-semibold">{data.store.name}</dd></div><div><dt className="text-xs text-text-muted">Currency</dt><dd className="mt-1">Nigerian Naira (NGN)</dd></div><div><dt className="text-xs text-text-muted">Address</dt><dd className="mt-1">{data.store.address}</dd></div><div><dt className="text-xs text-text-muted">Phone</dt><dd className="mt-1">{data.store.phone}</dd></div></dl></DemoCard><DemoCard title="Desktop capabilities" description="Available after installing Trova"><div className="grid gap-3 p-5 sm:grid-cols-2">{['Offline local storage','Receipt PDF downloads','Thermal printing','Customer display','Safe local backups','Team roles'].map(x=><div key={x} className="rounded-lg bg-bg-nav p-3 text-sm text-text-secondary">✓ {x}</div>)}</div></DemoCard></div></>
}
